package io.github.miklires.mreports;

import io.github.miklires.mreports.api.MReportsApi;import io.github.miklires.mreports.command.ReportCommand;import io.github.miklires.mreports.command.ReportsCommand;import io.github.miklires.mreports.gui.ReportGui;import io.github.miklires.mreports.gui.StaffQueueGui;import io.github.miklires.mreports.report.ReportService;import io.github.miklires.mreports.storage.ReportRepository;import io.github.miklires.mreports.util.PluginScheduler;import io.papermc.paper.plugin.lifecycle.event.types.LifecycleEvents;import java.time.Instant;import java.time.temporal.ChronoUnit;import org.bstats.bukkit.Metrics;import org.bukkit.plugin.ServicePriority;import org.bukkit.plugin.java.JavaPlugin;
public final class MReportsPlugin extends JavaPlugin {
    private PluginScheduler scheduler;private ReportRepository repository;private ReportService service;
    @Override public void onEnable(){saveDefaultConfig();scheduler=new PluginScheduler(this);try{repository=new ReportRepository(getDataFolder().toPath().resolve("data").resolve("mreports"));service=new ReportService(this,repository);ReportGui reportGui=new ReportGui(this,service);StaffQueueGui queueGui=new StaffQueueGui(this,service);getServer().getPluginManager().registerEvents(reportGui,this);getServer().getPluginManager().registerEvents(queueGui,this);getLifecycleManager().registerEventHandler(LifecycleEvents.COMMANDS,event->{event.registrar().register("report","Submit a player report",java.util.List.of(),new ReportCommand(service,reportGui));event.registrar().register("reports","Moderation report queue",java.util.List.of("mreports"),new ReportsCommand(this,service,queueGui));});long window=Math.clamp(getConfig().getLong("submission.duplicate-window-seconds",300),0L,31_536_000L)*1_000L;getServer().getServicesManager().register(MReportsApi.class,new ReportsApiService(repository,window),this,ServicePriority.Normal);int days=Math.clamp(getConfig().getInt("storage.retention-days",90),1,36_500);repository.purgeClosedBefore(Instant.now().minus(days,ChronoUnit.DAYS)).thenAccept(count->{if(count>0)getLogger().info("Purged "+count+" expired report(s)");});int id=Math.max(0,getConfig().getInt("metrics.bstats-id",0));if(getConfig().getBoolean("metrics.enabled",true)&&id>0)new Metrics(this,id);getLogger().info("mReports "+getPluginMeta().getVersion()+" is ready");}catch(RuntimeException e){getLogger().severe("mReports failed to start: "+e.getMessage());getServer().getPluginManager().disablePlugin(this);}}
    @Override public void onDisable(){getServer().getServicesManager().unregisterAll(this);if(repository!=null)repository.close();}
    public PluginScheduler scheduler(){return scheduler;}public void reloadRuntime(){reloadConfig();service.reload();}
}
