package io.github.miklires.mreports.storage;

import io.github.miklires.mreports.api.ReportStatus;
import io.github.miklires.mreports.api.ReportView;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public final class ReportRepository implements AutoCloseable {
    private final String jdbcUrl;
    private final ExecutorService executor = Executors.newSingleThreadExecutor(Thread.ofVirtual().name("mreports-db-", 0).factory());

    public ReportRepository(Path databaseFile) { this(prepareUrl(databaseFile)); }
    ReportRepository(String jdbcUrl) {
        this.jdbcUrl = jdbcUrl;
        try { Class.forName("org.h2.Driver"); migrate(); }
        catch (ClassNotFoundException | SQLException exception) { throw new IllegalStateException("Cannot initialize mReports storage", exception); }
    }
    private static String prepareUrl(Path file) {
        try { Files.createDirectories(file.toAbsolutePath().getParent()); }
        catch (java.io.IOException exception) { throw new IllegalStateException("Cannot create data directory", exception); }
        return "jdbc:h2:file:" + file.toAbsolutePath().toString().replace('\\', '/') + ";AUTO_SERVER=TRUE";
    }
    private Connection connection() throws SQLException { return DriverManager.getConnection(jdbcUrl, "sa", ""); }

    private void migrate() throws SQLException {
        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS schema_version(version INT PRIMARY KEY)");
            statement.executeUpdate("MERGE INTO schema_version(version) KEY(version) VALUES(1)");
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS reports(
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      reporter_id UUID NOT NULL, reporter_name VARCHAR(32) NOT NULL,
                      target_id UUID NOT NULL, target_name VARCHAR(32) NOT NULL,
                      category VARCHAR(48) NOT NULL, details VARCHAR(500) NOT NULL,
                      status VARCHAR(16) NOT NULL, handler_id UUID, handler_name VARCHAR(32),
                      duplicate_count INT NOT NULL DEFAULT 1, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL)
                    """);
            statement.executeUpdate("CREATE INDEX IF NOT EXISTS reports_queue_idx ON reports(status, updated_at)");
            statement.executeUpdate("CREATE INDEX IF NOT EXISTS reports_duplicate_idx ON reports(reporter_id,target_id,category,status)");
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS report_notes(
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_id BIGINT NOT NULL,
                      author_id UUID NOT NULL, author_name VARCHAR(32) NOT NULL, body VARCHAR(500) NOT NULL, created_at BIGINT NOT NULL,
                      FOREIGN KEY(report_id) REFERENCES reports(id) ON DELETE CASCADE)
                    """);
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS report_audit(
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_id BIGINT NOT NULL,
                      actor_id UUID, actor_name VARCHAR(32) NOT NULL, action VARCHAR(32) NOT NULL, detail VARCHAR(500) NOT NULL, created_at BIGINT NOT NULL,
                      FOREIGN KEY(report_id) REFERENCES reports(id) ON DELETE CASCADE)
                    """);
        }
    }

    public CompletableFuture<Submission> submit(UUID reporterId, String reporterName, UUID targetId, String targetName,
                                                 String category, String details, long duplicateWindowMillis) {
        return submitTask(() -> {
            long now = Instant.now().toEpochMilli();
            try (Connection connection = connection()) {
                connection.setAutoCommit(false);
                try {
                    ReportView duplicate = findDuplicate(connection, reporterId, targetId, category, now - duplicateWindowMillis);
                    if (duplicate != null) {
                        try (PreparedStatement statement = connection.prepareStatement(
                                "UPDATE reports SET duplicate_count=duplicate_count+1,details=?,updated_at=? WHERE id=?")) {
                            statement.setString(1, details); statement.setLong(2, now); statement.setLong(3, duplicate.id()); statement.executeUpdate();
                        }
                        audit(connection, duplicate.id(), reporterId, reporterName, "DUPLICATE_MERGED", details, now);
                        ReportView updated = find(connection, duplicate.id()).orElseThrow();
                        connection.commit();
                        return new Submission(updated, true);
                    }
                    long id;
                    try (PreparedStatement statement = connection.prepareStatement("""
                            INSERT INTO reports(reporter_id,reporter_name,target_id,target_name,category,details,status,duplicate_count,created_at,updated_at)
                            VALUES(?,?,?,?,?,?,'OPEN',1,?,?)
                            """, Statement.RETURN_GENERATED_KEYS)) {
                        statement.setObject(1, reporterId); statement.setString(2, reporterName);
                        statement.setObject(3, targetId); statement.setString(4, targetName);
                        statement.setString(5, category); statement.setString(6, details);
                        statement.setLong(7, now); statement.setLong(8, now); statement.executeUpdate();
                        try (ResultSet keys = statement.getGeneratedKeys()) { if (!keys.next()) throw new SQLException("No report id"); id = keys.getLong(1); }
                    }
                    audit(connection, id, reporterId, reporterName, "CREATED", category, now);
                    ReportView created = find(connection, id).orElseThrow();
                    connection.commit();
                    return new Submission(created, false);
                } catch (Throwable throwable) { connection.rollback(); throw throwable; }
            }
        });
    }

    public CompletableFuture<Optional<ReportView>> find(long id) {
        return submitTask(() -> { try (Connection connection = connection()) { return find(connection, id); } });
    }
    public CompletableFuture<List<ReportView>> queue(int limit) {
        return submitTask(() -> {
            List<ReportView> reports = new ArrayList<>();
            try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(
                    "SELECT * FROM reports WHERE status IN ('OPEN','CLAIMED') ORDER BY created_at ASC LIMIT ?")) {
                statement.setInt(1, Math.max(1, limit));
                try (ResultSet result = statement.executeQuery()) { while (result.next()) reports.add(map(result)); }
            }
            return List.copyOf(reports);
        });
    }

    public CompletableFuture<Boolean> claim(long id, UUID handlerId, String handlerName) {
        return transition(id, handlerId, handlerName, ReportStatus.CLAIMED, "CLAIMED", true);
    }
    public CompletableFuture<Boolean> close(long id, UUID handlerId, String handlerName, ReportStatus status, String note) {
        if (status != ReportStatus.RESOLVED && status != ReportStatus.REJECTED) throw new IllegalArgumentException("Invalid closing status");
        return submitTask(() -> {
            long now = Instant.now().toEpochMilli();
            try (Connection connection = connection()) {
                connection.setAutoCommit(false);
                try (PreparedStatement statement = connection.prepareStatement("""
                        UPDATE reports SET status=?,updated_at=? WHERE id=? AND status='CLAIMED' AND handler_id=?
                        """)) {
                    statement.setString(1, status.name()); statement.setLong(2, now); statement.setLong(3, id); statement.setObject(4, handlerId);
                    boolean changed = statement.executeUpdate() == 1;
                    if (changed) {
                        if (note != null && !note.isBlank()) note(connection, id, handlerId, handlerName, note, now);
                        audit(connection, id, handlerId, handlerName, status.name(), note == null ? "" : note, now);
                    }
                    connection.commit(); return changed;
                } catch (Throwable throwable) { connection.rollback(); throw throwable; }
            }
        });
    }
    public CompletableFuture<Boolean> addNote(long id, UUID authorId, String authorName, String body) {
        return submitTask(() -> {
            long now = Instant.now().toEpochMilli();
            try (Connection connection = connection()) {
                if (find(connection, id).isEmpty()) return false;
                note(connection, id, authorId, authorName, body, now); audit(connection, id, authorId, authorName, "NOTE_ADDED", body, now); return true;
            }
        });
    }
    public CompletableFuture<Integer> purgeClosedBefore(Instant cutoff) {
        return submitTask(() -> { try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(
                "DELETE FROM reports WHERE status IN ('RESOLVED','REJECTED') AND updated_at<?")) {
            statement.setLong(1, cutoff.toEpochMilli()); return statement.executeUpdate();
        }});
    }

    private CompletableFuture<Boolean> transition(long id, UUID actorId, String actorName, ReportStatus status, String action, boolean onlyOpen) {
        return submitTask(() -> {
            long now = Instant.now().toEpochMilli();
            String sql = "UPDATE reports SET status=?,handler_id=?,handler_name=?,updated_at=? WHERE id=?" + (onlyOpen ? " AND status='OPEN'" : "");
            try (Connection connection = connection()) {
                connection.setAutoCommit(false);
                try (PreparedStatement statement = connection.prepareStatement(sql)) {
                    statement.setString(1, status.name()); statement.setObject(2, actorId); statement.setString(3, actorName); statement.setLong(4, now); statement.setLong(5, id);
                    boolean changed = statement.executeUpdate() == 1;
                    if (changed) audit(connection, id, actorId, actorName, action, "", now);
                    connection.commit(); return changed;
                } catch (Throwable throwable) { connection.rollback(); throw throwable; }
            }
        });
    }

    private static ReportView findDuplicate(Connection connection, UUID reporter, UUID target, String category, long after) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                SELECT * FROM reports WHERE reporter_id=? AND target_id=? AND category=?
                AND status IN ('OPEN','CLAIMED') AND updated_at>=? ORDER BY updated_at DESC LIMIT 1 FOR UPDATE
                """)) {
            statement.setObject(1, reporter); statement.setObject(2, target); statement.setString(3, category); statement.setLong(4, after);
            try (ResultSet result = statement.executeQuery()) { return result.next() ? map(result) : null; }
        }
    }
    private static Optional<ReportView> find(Connection connection, long id) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM reports WHERE id=?")) {
            statement.setLong(1, id); try (ResultSet result = statement.executeQuery()) { return result.next() ? Optional.of(map(result)) : Optional.empty(); }
        }
    }
    private static ReportView map(ResultSet result) throws SQLException {
        return new ReportView(result.getLong("id"), result.getObject("reporter_id", UUID.class), result.getString("reporter_name"),
                result.getObject("target_id", UUID.class), result.getString("target_name"), result.getString("category"), result.getString("details"),
                ReportStatus.valueOf(result.getString("status")), result.getObject("handler_id", UUID.class), result.getString("handler_name"),
                result.getInt("duplicate_count"), Instant.ofEpochMilli(result.getLong("created_at")), Instant.ofEpochMilli(result.getLong("updated_at")));
    }
    private static void note(Connection c, long id, UUID actor, String name, String body, long now) throws SQLException {
        try (PreparedStatement s = c.prepareStatement("INSERT INTO report_notes(report_id,author_id,author_name,body,created_at) VALUES(?,?,?,?,?)")) {
            s.setLong(1,id); s.setObject(2,actor); s.setString(3,name); s.setString(4,body); s.setLong(5,now); s.executeUpdate();
        }
    }
    private static void audit(Connection c, long id, UUID actor, String name, String action, String detail, long now) throws SQLException {
        try (PreparedStatement s = c.prepareStatement("INSERT INTO report_audit(report_id,actor_id,actor_name,action,detail,created_at) VALUES(?,?,?,?,?,?)")) {
            s.setLong(1,id); s.setObject(2,actor); s.setString(3,name); s.setString(4,action); s.setString(5,detail); s.setLong(6,now); s.executeUpdate();
        }
    }
    private <T> CompletableFuture<T> submitTask(SqlTask<T> task) { return CompletableFuture.supplyAsync(() -> {
        try { return task.run(); } catch (RuntimeException e) { throw e; } catch (Exception e) { throw new IllegalStateException("Storage operation failed", e); }
    }, executor); }
    @Override public void close() { executor.close(); }
    @FunctionalInterface private interface SqlTask<T> { T run() throws Exception; }
    public record Submission(ReportView report, boolean merged) {}
}
