package io.github.miklires.mreports.storage;

import io.github.miklires.mreports.api.ReportStatus;
import io.github.miklires.mreports.api.ReportPriority;
import io.github.miklires.mreports.api.ReportView;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

public final class ReportRepository implements AutoCloseable {
    private final String jdbcUrl;
    private final ExecutorService executor = Executors.newSingleThreadExecutor(Thread.ofVirtual().name("mreports-db-", 0).factory());

    public ReportRepository(Path databaseFile) { this(prepareUrl(databaseFile)); }
    ReportRepository(String jdbcUrl) {
        this.jdbcUrl = jdbcUrl;
        try { Class.forName("org.h2.Driver"); migrate(); }
        catch (ClassNotFoundException | SQLException exception) { throw new IllegalStateException("Cannot initialize mReports storage", exception); }
    }
    private static String prepareUrl(Path file) {
        try { Files.createDirectories(file.toAbsolutePath().getParent()); }
        catch (java.io.IOException exception) { throw new IllegalStateException("Cannot create data directory", exception); }
        return "jdbc:h2:file:" + file.toAbsolutePath().toString().replace('\\', '/') + ";AUTO_SERVER=TRUE";
    }
    private Connection connection() throws SQLException { return DriverManager.getConnection(jdbcUrl, "sa", ""); }

    private void migrate() throws SQLException {
        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS schema_version(version INT PRIMARY KEY)");
            statement.executeUpdate("MERGE INTO schema_version(version) KEY(version) VALUES(2)");
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS reports(
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      reporter_id UUID NOT NULL, reporter_name VARCHAR(32) NOT NULL,
                      target_id UUID NOT NULL, target_name VARCHAR(32) NOT NULL,
                      category VARCHAR(48) NOT NULL, details VARCHAR(500) NOT NULL,
                      status VARCHAR(16) NOT NULL, priority VARCHAR(16) NOT NULL DEFAULT 'NORMAL', handler_id UUID, handler_name VARCHAR(32),
                      duplicate_count INT NOT NULL DEFAULT 1, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL)
                    """);
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS report_notes(
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_id BIGINT NOT NULL,
                      author_id UUID NOT NULL, author_name VARCHAR(32) NOT NULL, body VARCHAR(500) NOT NULL, created_at BIGINT NOT NULL,
                      FOREIGN KEY(report_id) REFERENCES reports(id) ON DELETE CASCADE)
                    """);
            statement.executeUpdate("""
                    CREATE TABLE IF NOT EXISTS report_audit(
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_id BIGINT NOT NULL,
                      actor_id UUID, actor_name VARCHAR(32) NOT NULL, action VARCHAR(32) NOT NULL, detail VARCHAR(500) NOT NULL, created_at BIGINT NOT NULL,
                      FOREIGN KEY(report_id) REFERENCES reports(id) ON DELETE CASCADE)
                    """);
            statement.executeUpdate("ALTER TABLE reports ALTER COLUMN details VARCHAR(2000)");
            statement.executeUpdate("ALTER TABLE reports ADD COLUMN IF NOT EXISTS priority VARCHAR(16) NOT NULL DEFAULT 'NORMAL'");
            statement.executeUpdate("ALTER TABLE report_notes ALTER COLUMN body VARCHAR(2000)");
            statement.executeUpdate("ALTER TABLE report_audit ALTER COLUMN detail VARCHAR(2000)");
            statement.executeUpdate("CREATE INDEX IF NOT EXISTS reports_target_idx ON reports(target_id, created_at)");
            statement.executeUpdate("CREATE INDEX IF NOT EXISTS reports_reporter_idx ON reports(reporter_id, created_at)");
            statement.executeUpdate("CREATE INDEX IF NOT EXISTS reports_queue_idx ON reports(status, updated_at)");
            statement.executeUpdate("CREATE INDEX IF NOT EXISTS reports_duplicate_idx ON reports(reporter_id,target_id,category,status)");
        }
    }

    public CompletableFuture<Submission> submit(UUID reporterId, String reporterName, UUID targetId, String targetName,
                                                 String category, String details, long duplicateWindowMillis) {
        reporterName = bounded(reporterName, 32, "reporter name");
        targetName = bounded(targetName, 32, "target name");
        category = bounded(category, 48, "category");
        details = bounded(details, 2000, "details");
        duplicateWindowMillis = Math.clamp(duplicateWindowMillis, 0L, 31_536_000_000L);
        String safeReporterName = reporterName;
        String safeTargetName = targetName;
        String safeCategory = category;
        String safeDetails = details;
        long safeDuplicateWindow = duplicateWindowMillis;
        return submitTask(() -> {
            long now = Instant.now().toEpochMilli();
            try (Connection connection = connection()) {
                connection.setAutoCommit(false);
                try {
                    ReportView duplicate = findDuplicate(connection, reporterId, targetId, safeCategory, now - safeDuplicateWindow);
                    if (duplicate != null) {
                        try (PreparedStatement statement = connection.prepareStatement(
                                "UPDATE reports SET duplicate_count=duplicate_count+1,details=?,updated_at=? WHERE id=?")) {
                            statement.setString(1, safeDetails); statement.setLong(2, now); statement.setLong(3, duplicate.id()); statement.executeUpdate();
                        }
                        audit(connection, duplicate.id(), reporterId, safeReporterName, "DUPLICATE_MERGED", safeDetails, now);
                        ReportView updated = find(connection, duplicate.id()).orElseThrow();
                        connection.commit();
                        return new Submission(updated, true);
                    }
                    long id;
                    try (PreparedStatement statement = connection.prepareStatement("""
                            INSERT INTO reports(reporter_id,reporter_name,target_id,target_name,category,details,status,duplicate_count,created_at,updated_at)
                            VALUES(?,?,?,?,?,?,'OPEN',1,?,?)
                            """, Statement.RETURN_GENERATED_KEYS)) {
                        statement.setObject(1, reporterId); statement.setString(2, safeReporterName);
                        statement.setObject(3, targetId); statement.setString(4, safeTargetName);
                        statement.setString(5, safeCategory); statement.setString(6, safeDetails);
                        statement.setLong(7, now); statement.setLong(8, now); statement.executeUpdate();
                        try (ResultSet keys = statement.getGeneratedKeys()) { if (!keys.next()) throw new SQLException("No report id"); id = keys.getLong(1); }
                    }
                    audit(connection, id, reporterId, safeReporterName, "CREATED", safeCategory, now);
                    ReportView created = find(connection, id).orElseThrow();
                    connection.commit();
                    return new Submission(created, false);
                } catch (Throwable throwable) { connection.rollback(); throw throwable; }
            }
        });
    }

    public CompletableFuture<Optional<ReportView>> find(long id) {
        if (id < 1) return CompletableFuture.completedFuture(Optional.empty());
        return submitTask(() -> { try (Connection connection = connection()) { return find(connection, id); } });
    }
    public CompletableFuture<List<ReportView>> queue(int limit) {
        return submitTask(() -> {
            List<ReportView> reports = new ArrayList<>();
            try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(
                    "SELECT * FROM reports WHERE status IN ('OPEN','CLAIMED') ORDER BY created_at ASC LIMIT ?")) {
                statement.setInt(1, Math.clamp(limit, 1, 500));
                try (ResultSet result = statement.executeQuery()) { while (result.next()) reports.add(map(result)); }
            }
            return List.copyOf(reports);
        });
    }

    public CompletableFuture<Boolean> claim(long id, UUID handlerId, String handlerName) {
        return transition(id, handlerId, handlerName, ReportStatus.CLAIMED, "CLAIMED", true);
    }
    public CompletableFuture<Boolean> release(long id, UUID handlerId, String handlerName) {
        return submitTask(() -> {
            long now = Instant.now().toEpochMilli();
            try (Connection connection = connection()) {
                connection.setAutoCommit(false);
                try (PreparedStatement statement = connection.prepareStatement(
                        "UPDATE reports SET status='OPEN',handler_id=NULL,handler_name=NULL,updated_at=? WHERE id=? AND status='CLAIMED' AND handler_id=?")) {
                    statement.setLong(1, now); statement.setLong(2, id); statement.setObject(3, handlerId);
                    boolean changed = statement.executeUpdate() == 1;
                    if (changed) audit(connection, id, handlerId, bounded(handlerName, 32, "handler name"), "RELEASED", "", now);
                    connection.commit(); return changed;
                } catch (Throwable throwable) { connection.rollback(); throw throwable; }
            }
        });
    }
    public CompletableFuture<Boolean> setPriority(long id, UUID actorId, String actorName, ReportPriority priority) {
        return submitTask(() -> {
            long now = Instant.now().toEpochMilli();
            try (Connection connection = connection()) {
                connection.setAutoCommit(false);
                try (PreparedStatement statement = connection.prepareStatement(
                        "UPDATE reports SET priority=?,updated_at=? WHERE id=? AND status IN ('OPEN','CLAIMED')")) {
                    statement.setString(1, priority.name()); statement.setLong(2, now); statement.setLong(3, id);
                    boolean changed = statement.executeUpdate() == 1;
                    if (changed) audit(connection, id, actorId, bounded(actorName, 32, "actor name"), "PRIORITY_CHANGED", priority.name(), now);
                    connection.commit(); return changed;
                } catch (Throwable throwable) { connection.rollback(); throw throwable; }
            }
        });
    }
    public CompletableFuture<List<ReportView>> history(UUID playerId, int limit) {
        return list("SELECT * FROM reports WHERE reporter_id=? OR target_id=? ORDER BY created_at DESC LIMIT ?", statement -> {
            statement.setObject(1, playerId); statement.setObject(2, playerId); statement.setInt(3, Math.clamp(limit, 1, 200));
        });
    }
    public CompletableFuture<List<ReportView>> submittedBy(UUID reporterId, int limit) {
        return list("SELECT * FROM reports WHERE reporter_id=? ORDER BY created_at DESC LIMIT ?", statement -> {
            statement.setObject(1, reporterId); statement.setInt(2, Math.clamp(limit, 1, 200));
        });
    }
    public CompletableFuture<List<ReportView>> search(String query, int limit) {
        String term = "%" + bounded(query, 64, "search query").toLowerCase(java.util.Locale.ROOT) + "%";
        return list("SELECT * FROM reports WHERE LOWER(reporter_name) LIKE ? OR LOWER(target_name) LIKE ? OR LOWER(category) LIKE ? OR LOWER(COALESCE(handler_name,'')) LIKE ? ORDER BY updated_at DESC LIMIT ?", statement -> {
            for (int index = 1; index <= 4; index++) statement.setString(index, term);
            statement.setInt(5, Math.clamp(limit, 1, 200));
        });
    }
    public CompletableFuture<Boolean> close(long id, UUID handlerId, String handlerName, ReportStatus status, String note) {
        if (status != ReportStatus.RESOLVED && status != ReportStatus.REJECTED) throw new IllegalArgumentException("Invalid closing status");
        handlerName = bounded(handlerName, 32, "handler name");
        note = note == null || note.isBlank() ? "" : bounded(note, 2000, "note");
        String safeHandler = handlerName;
        String safeNote = note;
        return submitTask(() -> {
            long now = Instant.now().toEpochMilli();
            try (Connection connection = connection()) {
                connection.setAutoCommit(false);
                try (PreparedStatement statement = connection.prepareStatement("""
                        UPDATE reports SET status=?,updated_at=? WHERE id=? AND status='CLAIMED' AND handler_id=?
                        """)) {
                    statement.setString(1, status.name()); statement.setLong(2, now); statement.setLong(3, id); statement.setObject(4, handlerId);
                    boolean changed = statement.executeUpdate() == 1;
                    if (changed) {
                        if (!safeNote.isBlank()) note(connection, id, handlerId, safeHandler, safeNote, now);
                        audit(connection, id, handlerId, safeHandler, status.name(), safeNote, now);
                    }
                    connection.commit(); return changed;
                } catch (Throwable throwable) { connection.rollback(); throw throwable; }
            }
        });
    }
    public CompletableFuture<Boolean> addNote(long id, UUID authorId, String authorName, String body) {
        authorName = bounded(authorName, 32, "author name");
        body = bounded(body, 2000, "note");
        String safeAuthor = authorName;
        String safeBody = body;
        return submitTask(() -> {
            long now = Instant.now().toEpochMilli();
            try (Connection connection = connection()) {
                if (find(connection, id).isEmpty()) return false;
                note(connection, id, authorId, safeAuthor, safeBody, now); audit(connection, id, authorId, safeAuthor, "NOTE_ADDED", safeBody, now); return true;
            }
        });
    }
    public CompletableFuture<Integer> purgeClosedBefore(Instant cutoff) {
        return submitTask(() -> { try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(
                "DELETE FROM reports WHERE status IN ('RESOLVED','REJECTED') AND updated_at<?")) {
            statement.setLong(1, cutoff.toEpochMilli()); return statement.executeUpdate();
        }});
    }

    private CompletableFuture<Boolean> transition(long id, UUID actorId, String actorName, ReportStatus status, String action, boolean onlyOpen) {
        actorName = bounded(actorName, 32, "actor name");
        String safeActorName = actorName;
        return submitTask(() -> {
            long now = Instant.now().toEpochMilli();
            String sql = "UPDATE reports SET status=?,handler_id=?,handler_name=?,updated_at=? WHERE id=?" + (onlyOpen ? " AND status='OPEN'" : "");
            try (Connection connection = connection()) {
                connection.setAutoCommit(false);
                try (PreparedStatement statement = connection.prepareStatement(sql)) {
                    statement.setString(1, status.name()); statement.setObject(2, actorId); statement.setString(3, safeActorName); statement.setLong(4, now); statement.setLong(5, id);
                    boolean changed = statement.executeUpdate() == 1;
                    if (changed) audit(connection, id, actorId, safeActorName, action, "", now);
                    connection.commit(); return changed;
                } catch (Throwable throwable) { connection.rollback(); throw throwable; }
            }
        });
    }

    private static ReportView findDuplicate(Connection connection, UUID reporter, UUID target, String category, long after) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                SELECT * FROM reports WHERE reporter_id=? AND target_id=? AND category=?
                AND status IN ('OPEN','CLAIMED') AND updated_at>=? ORDER BY updated_at DESC LIMIT 1 FOR UPDATE
                """)) {
            statement.setObject(1, reporter); statement.setObject(2, target); statement.setString(3, category); statement.setLong(4, after);
            try (ResultSet result = statement.executeQuery()) { return result.next() ? map(result) : null; }
        }
    }
    private static Optional<ReportView> find(Connection connection, long id) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM reports WHERE id=?")) {
            statement.setLong(1, id); try (ResultSet result = statement.executeQuery()) { return result.next() ? Optional.of(map(result)) : Optional.empty(); }
        }
    }
    private static ReportView map(ResultSet result) throws SQLException {
        return new ReportView(result.getLong("id"), result.getObject("reporter_id", UUID.class), result.getString("reporter_name"),
                result.getObject("target_id", UUID.class), result.getString("target_name"), result.getString("category"), result.getString("details"),
                ReportStatus.valueOf(result.getString("status")), ReportPriority.valueOf(result.getString("priority")), result.getObject("handler_id", UUID.class), result.getString("handler_name"),
                result.getInt("duplicate_count"), Instant.ofEpochMilli(result.getLong("created_at")), Instant.ofEpochMilli(result.getLong("updated_at")));
    }
    private static void note(Connection c, long id, UUID actor, String name, String body, long now) throws SQLException {
        try (PreparedStatement s = c.prepareStatement("INSERT INTO report_notes(report_id,author_id,author_name,body,created_at) VALUES(?,?,?,?,?)")) {
            s.setLong(1,id); s.setObject(2,actor); s.setString(3,name); s.setString(4,body); s.setLong(5,now); s.executeUpdate();
        }
    }
    private static void audit(Connection c, long id, UUID actor, String name, String action, String detail, long now) throws SQLException {
        try (PreparedStatement s = c.prepareStatement("INSERT INTO report_audit(report_id,actor_id,actor_name,action,detail,created_at) VALUES(?,?,?,?,?,?)")) {
            s.setLong(1,id); s.setObject(2,actor); s.setString(3,name); s.setString(4,action); s.setString(5,detail); s.setLong(6,now); s.executeUpdate();
        }
    }
    private <T> CompletableFuture<T> submitTask(SqlTask<T> task) { return CompletableFuture.supplyAsync(() -> {
        try { return task.run(); } catch (RuntimeException e) { throw e; } catch (Exception e) { throw new IllegalStateException("Storage operation failed", e); }
    }, executor); }
    private CompletableFuture<List<ReportView>> list(String sql, SqlBinder binder) {
        return submitTask(() -> {
            List<ReportView> reports = new ArrayList<>();
            try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(sql)) {
                binder.bind(statement);
                try (ResultSet result = statement.executeQuery()) { while (result.next()) reports.add(map(result)); }
            }
            return List.copyOf(reports);
        });
    }
    private static String bounded(String value, int maximum, String name) {
        if (value == null || value.isBlank() || value.length() > maximum || value.chars().anyMatch(Character::isISOControl))
            throw new IllegalArgumentException("Invalid " + name);
        return value.trim();
    }
    @Override public void close() {
        executor.shutdown();
        try { if (!executor.awaitTermination(5, TimeUnit.SECONDS)) executor.shutdownNow(); }
        catch (InterruptedException exception) { executor.shutdownNow(); Thread.currentThread().interrupt(); }
    }
    @FunctionalInterface private interface SqlTask<T> { T run() throws Exception; }
    @FunctionalInterface private interface SqlBinder { void bind(PreparedStatement statement) throws SQLException; }
    public record Submission(ReportView report, boolean merged) {}
}
